### ISSUE TITLE
An optimization suggestion regarding the date picker component

### ISSUE THREAD

**Issue by Createwj** [Casual-UI/svelte#14]
![image](https://user-images.githubusercontent.com/24564508/220607314-23336520-aa5b-4b3f-985d-4bec73679c1b.png)

After the user selects the time, whether the popup window can be modified to automatically close

**Comment by Blackman99** [comment]
Thanks for the feedback!
The issue has been fixed in this PR: #15

**Comment by Blackman99** [comment]
Close this by fixing in [this release](https://github.com/Casual-UI/svelte/releases/tag/%40casual-ui%2Fsvelte%400.1.0)
